title: MSVC Gallery with Face Matching
description: 3 Semesterarbeit für Cloud Native Engineer Studium
baseurl: "/docs" # the subpath of your site, e.g., "/blog"
url: "https://noluchs.github.io/MSCV-Gallery-with-Face-Matching/" # the base hostname & protocol for your site, e.g., "http://example.com"

remote_theme: just-the-docs/just-the-docs

aux_links:
  Projektplanung: https://github.com/users/noluchs/projects/6
